version: "3.8"
services:
  server:
    build: .
    restart: always
     ports:
       -8080:8080
     depends_on:
       -mysql01
  mysqldb:
    platform: linux/x86_64
    image: "mysql:5.7"
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_DATABASE: springbootmysqldocker
      MYSQL_USER: nghiant
      MYSQL_PASSWORD: nghiant
      MYSQL_ROOT_PASSWORD: Nghiant@123